import { StyleSheet } from 'react-native';
import { SPACING } from '@/constants';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  backButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  cartButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  cartButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  logoutButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  logoutButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
});
