import { StyleSheet } from 'react-native';
import { SPACING, COLORS } from '@/constants';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  backButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  cartButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  cartButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  logoutButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  logoutButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  bellButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  bellButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bellButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  ratingButton: {
    position: 'absolute',
    right: SPACING.MD,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
  },
  ratingButtonBackground: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingButtonImage: {
    width: 40,
    height: 36,
    resizeMode: 'cover',
  },
  rightLabelButton: {
    position: 'absolute',
    right: SPACING.MD,
    paddingVertical: SPACING.SM,
    paddingHorizontal: SPACING.XS,
    zIndex: 1,
  },
  rightLabelText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '600',
  },
});
