import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    marginBottom: SPACING.MD,
    height: 148,
  },
  imageContainer: {
    width: 139,
    height: 148,
    position: 'relative',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 66,
    backgroundColor: 'rgba(0, 0, 0, 0.128)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  liveButton: {
    backgroundColor: '#fdfbee',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
  },
  liveButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  infoContainer: {
    width: 222,
    height: 148,
    backgroundColor: 'rgba(237, 236, 128, 0.8)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingTop: 8,
    paddingBottom: SPACING.MD,
    paddingHorizontal: SPACING.LG,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  contentWrapper: {
    flex: 1,
    justifyContent: 'center',
    gap: SPACING.LG,
  },
  titleSection: {
    gap: SPACING.SM,
  },
  cameraIcon: {
    width: 24,
    height: 24,
    marginBottom: SPACING.XS,
  },
  titleContainer: {
    gap: 0,
  },
  title: {
    fontSize: 14,
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
    lineHeight: 14,
  },
  host: {
    fontSize: 12,
    fontWeight: '500',
    color: '#001137',
    letterSpacing: 0.2,
    lineHeight: 12,
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    height: 16,
  },
  timeLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6e6a6a',
    letterSpacing: 0.2,
  },
  time: {
    fontSize: 12,
    fontWeight: '500',
    color: '#001137',
    letterSpacing: 0.2,
  },
});
