import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SPACING, BORDER_RADIUS } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fbf7e5',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.LG,
    paddingHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  contentContainer: {
    gap: SPACING.LG,
    marginBottom: SPACING.SM,
  },
  badgeContainer: {
    width: 110,
  },
  authorSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    marginBottom: SPACING.SM,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  avatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.BACKGROUND,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authorName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  titleContainer: {
    marginBottom: SPACING.XS,
  },
  title: {
    fontSize: 20,
    fontWeight: '400',
    color: '#001137',
    lineHeight: 20,
  },
  description: {
    fontSize: 14,
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 14,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: SPACING.SM,
  },
  seeMoreButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  seeMoreButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  commentsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
  },
  commentsCount: {
    fontSize: 12,
    fontWeight: '500',
    color: '#0154f8',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  commentsSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
});
