import { StyleSheet } from 'react-native';
import { COLORS, SPACING, FONT_SIZES } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.LG,
    gap: SPACING.MD,
  },
  title: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
    color: COLORS.BLACK,
    fontFamily: 'DM Sans',
    textAlign: 'center',
    flex: 1,
    marginRight: 40 + SPACING.MD,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingTop: SPACING.XL,
  },
  avatar: {
    width: 125,
    height: 116,
    borderRadius: 63,
  },
  avatarPlaceholder: {
    width: 125,
    height: 116,
    borderRadius: 63,
    backgroundColor: COLORS.PRIMARY.LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactName: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '400',
    color: COLORS.NEUTRAL.LOW.DARK,
    fontFamily: 'DM Sans',
    lineHeight: 22,
    letterSpacing: 0.2,
    textAlign: 'center',
    marginTop: 10,
  },
  buttonsContainer: {
    paddingHorizontal: SPACING.MD,
    paddingBottom: SPACING.XL,
    gap: SPACING.SM,
  },
  deleteButton: {
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    minHeight: 48,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  deleteButtonText: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
    color: COLORS.WHITE,
    fontFamily: 'DM Sans',
    textAlign: 'center',
  },
  blockButton: {
    backgroundColor: 'rgba(240,238,225,0.16)',
    borderWidth: 1,
    borderColor: COLORS.NEUTRAL.LOW.PURE,
    minHeight: 48,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  blockButtonText: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    textAlign: 'center',
  },
});
