import { StyleSheet } from 'react-native';
import { SPACING, FONT_SIZES, COLORS, BORDER_RADIUS } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    gap: SPACING.MD,
  },
  sectionTitle: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: COLORS.BLACK,
    lineHeight: 20,
  },
  communityCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: BORDER_RADIUS.LG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingTop: SPACING.MD,
    paddingBottom: 4,
    paddingHorizontal: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.MD,
  },
  membersBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  avatarGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: -SPACING.MD,
  },
  avatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginLeft: -SPACING.MD,
    borderWidth: 2,
    borderColor: '#fbf7e5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarBlue: {
    backgroundColor: '#0154f8',
  },
  avatarPink: {
    backgroundColor: '#f6cffb',
  },
  avatarGreen: {
    backgroundColor: '#EDEC80',
  },
  avatarText: {
    fontSize: FONT_SIZES.XS,
    fontWeight: '700',
    color: COLORS.BLACK,
    fontFamily: 'DM Sans',
  },
  membersText: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#6e6a6a',
    letterSpacing: 0.2,
  },
  newPostBadge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    minHeight: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  newPostText: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#F6DEA9',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  communityContent: {
    gap: SPACING.MD,
  },
  communityTitle: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: '#001137',
    lineHeight: 20,
  },
  communityDescription: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.SM,
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
    lineHeight: 14,
  },
  postsSectionTitle: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#001137',
    marginTop: SPACING.XS,
  },
  postsScrollView: {
    maxHeight: 384,
    marginTop: SPACING.XS,
  },
  postCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: BORDER_RADIUS.LG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    padding: SPACING.MD,
    marginBottom: SPACING.XS,
    gap: SPACING.XS,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
  },
  postAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  postAvatarPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.BACKGROUND,
    justifyContent: 'center',
    alignItems: 'center',
  },
  postAuthorName: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#6e6a6a',
    letterSpacing: 0.2,
  },
  postTitle: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.SM,
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
    lineHeight: 14,
    marginTop: SPACING.XS,
  },
  postContent: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#6e6a6a',
    lineHeight: 12,
    marginTop: SPACING.XS,
  },
  postFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: SPACING.XS,
  },
  postAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postActionText: {
    fontFamily: 'DM Sans',
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: '#0154f8',
    letterSpacing: 0.2,
  },
});
