import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  modalRoot: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.36)',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  panel: {
    flex: 1,
    maxWidth: 360,
    width: '92%',
    backgroundColor: '#FBF7E5',
    borderTopRightRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: SPACING.LG,
    paddingTop: 52,
    paddingBottom: SPACING.MD,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 6,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  avatarWithText: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  closeButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 39,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e0e0e0',
  },
  avatarPlaceholder: {
    width: 39,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9E9E9',
  },
  userDetails: {
    flexShrink: 1,
    justifyContent: 'center',
  },
  userName: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: '#001137',
    fontWeight: '400',
    fontFamily: 'DM Sans',
  },
  userEmail: {
    fontSize: 12,
    lineHeight: 22,
    letterSpacing: 0.2,
    color: '#6e6a6a',
    fontWeight: '500',
    fontFamily: 'DM Sans',
  },
  itemsContainer: {
    flex: 1,
  },
  menuItem: {
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItemDisabled: {
    opacity: 0.32,
    paddingTop: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuItemLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: '#001137',
    fontWeight: '700',
    fontFamily: 'DM Sans',
  },
  menuItemDisabledLabel: {
    fontSize: 16,
    lineHeight: 24,
    color: '#001137',
    fontWeight: '700',
    fontFamily: 'DM Sans',
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#DCDCD0',
    width: '100%',
  },
  bottomButtons: {
    gap: 8,
    marginTop: 12,
  },
  deleteButton: {
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 24,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  deleteButtonDisabled: {
    opacity: 0.6,
  },
  deleteButtonLabel: {
    color: '#001137',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'DM Sans',
  },
  webDeletionLinkText: {
    fontSize: 12,
    color: COLORS.TEXT_LIGHT,
    textAlign: 'center',
    textDecorationLine: 'underline',
    fontFamily: 'DM Sans',
    marginTop: 4,
  },
});
