import { ImageStyle, StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 170,
  },
  topSection: {
    width: '100%',
    backgroundColor: COLORS.BACKGROUND_SECONDARY,
    borderBottomLeftRadius: 64,
    borderBottomRightRadius: 64,
    overflow: 'hidden',
  },
  headerContent: {
    width: '100%',
    paddingBottom: SPACING.XL,
    gap: 24,
    marginTop: 31,
    paddingHorizontal: SPACING.MD,
  },
  titleAdornment: {
    position: 'absolute',
  } as ImageStyle,
  content: {
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: 32,
    width: '100%',
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.XL,
    paddingBottom: SPACING.LG,
  },
  invitationSection: {
    width: '100%',
    alignItems: 'flex-start',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  invitationQuestion: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 20,
    marginBottom: 8,
    width: '60%',
  },
  infoSection: {
    width: '100%',
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    paddingHorizontal: 0,
  },
  infoText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 24,
    textAlign: 'left',
  },
  sectionLabel: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: SPACING.SM,
  },
  fieldsContainer: {
    width: '100%',
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  fieldRow: {
    width: '100%',
    alignSelf: 'stretch',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.BACKGROUND,
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
  },
  buttonGroup: {
    position: 'relative',
    left: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 0,
    paddingTop: 0,
  },
  scrollContentInner: {
    flexGrow: 1,
    width: '100%',
  },
  genderLabel: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 22,
    marginBottom: 8,
  },
  genderTouchable: {
    alignSelf: 'stretch',
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 42,
  },
  genderTouchableText: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 20,
    flex: 1,
  },
  genderPlaceholder: {
    color: COLORS.TEXT_LIGHT,
  },
  genderModalOverlay: {
    flex: 1,
    backgroundColor: COLORS.BLACK + '80',
    justifyContent: 'flex-end',
  },
  genderModalContent: {
    backgroundColor: COLORS.BACKGROUND,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.XXL + 24,
  },
  genderModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.LG,
  },
  genderModalTitle: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 18,
    fontWeight: '600',
  },
  genderOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.MD,
    paddingHorizontal: SPACING.SM,
    borderRadius: 12,
    marginBottom: SPACING.XS,
  },
  genderOptionSelected: {
    backgroundColor: 'rgba(1, 84, 248, 0.08)',
  },
  genderOptionText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '400',
    flex: 1,
  },
  genderOptionTextSelected: {
    fontWeight: '600',
    color: COLORS.PRIMARY.PURE,
  },
  sectionBlock: {
    marginTop: SPACING.XL,
    width: '100%',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginBottom: SPACING.SM,
  },
  sectionOptional: {
    color: COLORS.TEXT_LIGHT,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
  },
  sectionInfoText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
    marginBottom: SPACING.MD,
  },
  inputLabel: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 8,
  },
  healthPlanTouchable: {
    alignSelf: 'stretch',
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 42,
  },
  healthPlanTouchableText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    flex: 1,
  },
  healthPlanPlaceholder: {
    color: COLORS.TEXT_LIGHT,
  },
  benefitsHint: {
    color: COLORS.TEXT_LIGHT,
    fontFamily: 'DM Sans',
    fontSize: 12,
    fontWeight: '400',
    marginBottom: SPACING.MD,
  },
  benefitsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.SM,
  },
  benefitChip: {
    paddingVertical: SPACING.SM,
    paddingHorizontal: SPACING.MD,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.NEUTRAL.LOW.PURE,
    backgroundColor: 'transparent',
  },
  benefitChipSelected: {
    backgroundColor: COLORS.PRIMARY.PURE,
    borderColor: COLORS.PRIMARY.PURE,
  },
  benefitChipText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
  },
  benefitChipTextSelected: {
    color: COLORS.WHITE,
    fontWeight: '600',
  },
});
