import { StyleSheet, Dimensions } from 'react-native';
import { BORDER_RADIUS, COLORS, SPACING } from '@/constants';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
    backgroundColor: '#F4F3EC',
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  backgroundImageStyle: {
    resizeMode: 'cover',
    opacity: 0.1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  heroSection: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.6,
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  heroImageStyle: {
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 32,
    paddingBottom: 30,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  heroGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 327,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  heroContent: {
    zIndex: 1,
  },
  badgesContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 16,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#f6dea9',
    letterSpacing: 0.2,
  },
  heroTitle: {
    fontSize: 16,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
    marginTop: 10,
  },
  heroName: {
    fontSize: 24,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 8,
  },
  heroFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  heroStats: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  followButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  followButtonText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#FFFFFF',
  },
  content: {
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.LG,
  },
  tabsContainer: {
    marginBottom: SPACING.LG,
  },
  aboutSection: {
    marginBottom: SPACING.XL,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.MD,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
  },
  descriptionText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    lineHeight: 22,
  },
  programsSection: {
    marginBottom: SPACING.XL,
  },
  productsSection: {
    marginBottom: SPACING.XL,
    gap: SPACING.MD,
  },
  productRow: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: SPACING.MD,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  productRowImage: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginRight: SPACING.MD,
  },
  productRowContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  productRowCategory: {
    alignSelf: 'flex-start',
    backgroundColor: '#F5F5F5',
    borderRadius: 999,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
    marginBottom: SPACING.XS,
  },
  productRowCategoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666666',
  },
  productRowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#000000',
    marginBottom: SPACING.XS,
  },
  productRowFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productRowPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
  },
  productRowAddButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: SPACING.MD,
  },
  talkButtonContainer: {
    marginBottom: SPACING.XL,
  },
  talkButton: {
    width: '100%',
  },
  feedbackSection: {
    backgroundColor: '#DBE7DB',
    borderRadius: 20,
    padding: SPACING.LG,
    marginTop: SPACING.XL,
  },
  feedbackHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.MD,
  },
  feedbackTitle: {
    fontSize: 18,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
  },
  feedbackRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  feedbackRatingText: {
    fontSize: 16,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  reviewsList: {
    gap: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  reviewCard: {
    backgroundColor: '#F9F7F4',
    borderRadius: 12,
    padding: SPACING.MD,
  },
  reviewUserName: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: '#001137',
    marginBottom: 4,
  },
  reviewComment: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    marginBottom: 8,
  },
  reviewFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewDate: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#666666',
  },
  reviewRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewRatingText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  seeAllButton: {
    alignItems: 'center',
    paddingVertical: SPACING.MD,
  },
  seeAllText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: '#001137',
  },
  communityPreviewContainer: {
    marginTop: SPACING.MD,
  },
  loadingContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
  },
});
