import { StyleSheet } from 'react-native';
import { SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    gap: 8,
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 328,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: '#001137',
  },
  checkContainer: {
    width: 30,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#8fa3a1',
  },
  content: {
    width: 305,
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 319,
    borderRadius: 16,
  },
  questionContainer: {
    width: '100%',
    gap: 16,
    alignItems: 'flex-end',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1.5,
    borderColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    minHeight: 36,
  },
  editButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
  },
  question: {
    fontSize: 14,
    fontWeight: '400',
    color: '#001137',
    lineHeight: 20,
    width: '100%',
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XS,
    width: 287,
  },
  optionButton: {
    minHeight: 32,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 0,
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(143, 163, 161, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    minWidth: '45%',
  },
  optionButtonSelected: {
    backgroundColor: '#8fa3a1',
  },
  optionText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#8fa3a1',
  },
  optionTextSelected: {
    color: '#fbf7e5',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#001137',
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    borderRadius: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    minHeight: 48,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
  },
  submitButtonSubmitted: {
    backgroundColor: '#001137',
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#ffffff',
  },
  submitButtonTextSubmitted: {
    color: '#ffffff',
  },
});

