import { StyleSheet } from 'react-native';
import { SPACING, FONT_SIZES } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'rgba(237, 236, 128, 0.8)',
    borderRadius: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingVertical: SPACING.LG,
    paddingHorizontal: SPACING.SM,
    marginBottom: SPACING.MD,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  closeButton: {
    position: 'absolute',
    top: SPACING.SM,
    right: SPACING.SM,
    zIndex: 1,
    padding: SPACING.XS,
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  content: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: SPACING.SM,
    marginTop: -8,
    paddingRight: SPACING.LG,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.SM,
    width: '100%',
  },
  iconButton: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  message: {
    flex: 1,
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0.2,
    color: '#001137',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 16,
    marginLeft: 48, // Align with message text (icon width + gap)
  },
  dateText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    lineHeight: 16,
    color: '#6e6a6a',
  },
  separator: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    lineHeight: 16,
    color: '#6e6a6a',
  },
  timeLabel: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    lineHeight: 16,
    color: '#6e6a6a',
  },
  timeValue: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    lineHeight: 16,
    color: '#001137',
  },
});

