import { StyleSheet } from 'react-native';
import { SPACING, BORDER_RADIUS } from '@/constants';

const COLORS = {
  TEXT_DARK: '#001137',
  TEXT_LIGHT: '#666666',
  PRIMARY: '#0154f8',
  BORDER: '#b2b2b2',
  BLACK: '#000000',
};

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.MD,
  },
  modalContainer: {
    backgroundColor: 'rgba(251, 247, 229, 0.96)',
    borderRadius: BORDER_RADIUS.XL,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    width: '100%',
    maxWidth: 360,
    maxHeight: '80%',
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.MD,
    paddingHorizontal: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
  },
  headerSpacer: {
    flex: 1,
  },
  closeButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flexGrow: 1,
    flexShrink: 1,
    width: '100%',
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    gap: 0,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251, 247, 229, 0.8)',
    borderRadius: BORDER_RADIUS.MD,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: SPACING.MD,
    width: '47%',
    marginHorizontal: '1.5%',
    marginBottom: SPACING.XS,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    gap: 9,
  },
  filterOptionSelected: {
    backgroundColor: 'rgba(240, 238, 225, 0.9)',
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
  },
  optionIcon: {
    fontSize: 16,
    width: 17,
    height: 15.222,
  },
  optionText: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.TEXT_DARK,
    flex: 1,
    textAlign: 'center',
    fontFamily: 'DM Sans',
  },
  optionTextSelected: {
    fontWeight: '500',
    color: COLORS.PRIMARY,
  },
  saveButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: BORDER_RADIUS.MD,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingVertical: 9,
    paddingHorizontal: SPACING.MD,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.TEXT_LIGHT,
    textAlign: 'center',
    fontFamily: 'DM Sans',
  },
  emptyContainer: {
    paddingVertical: SPACING.XL,
    alignItems: 'center',
    width: '100%',
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.TEXT_LIGHT,
  },
});

