import { StyleSheet, Dimensions } from 'react-native';
import { BORDER_RADIUS, COLORS, SPACING } from '@/constants';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.MD,
    paddingTop: 50,
    paddingBottom: SPACING.SM,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  logoContainer: {
    flex: 1,
    alignItems: 'center',
  },
  favoriteButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
  },
  scrollContent: {
    paddingBottom: SPACING.XXL,
  },
  heroSection: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.5,
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2E7D32',
  },
  heroProductCard: {
    position: 'absolute',
    bottom: SPACING.LG,
    right: SPACING.MD,
    backgroundColor: '#FFFFFF',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
    width: SCREEN_WIDTH * 0.7,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  heroCardTags: {
    flexDirection: 'row',
    gap: SPACING.SM,
    flexWrap: 'wrap',
    marginBottom: SPACING.SM,
  },
  heroCardTag: {
    backgroundColor: '#2E7D32',
    borderRadius: 999,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
  },
  heroCardTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  heroCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#001137',
    marginBottom: SPACING.SM,
  },
  heroCardPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroCardPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#001137',
  },
  heroCardCartButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    backgroundColor: '#F4F3EC',
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.LG,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: BORDER_RADIUS.MD,
    padding: 4,
    marginBottom: SPACING.LG,
  },
  tab: {
    flex: 1,
    paddingVertical: SPACING.SM,
    alignItems: 'center',
    borderRadius: BORDER_RADIUS.SM,
  },
  tabActive: {
    backgroundColor: '#FFF9C4',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },
  tabTextActive: {
    color: '#000000',
    fontWeight: '600',
  },
  productTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000000',
    marginBottom: SPACING.MD,
  },
  productDescription: {
    fontSize: 15,
    lineHeight: 22,
    color: '#666666',
    marginBottom: SPACING.LG,
  },
  addToCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#001137',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
    marginBottom: SPACING.MD,
    gap: SPACING.SM,
  },
  providerAvatarSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  addToCartText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ratingBadgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  providerButton: {
    backgroundColor: '#E0E0E0',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
    marginBottom: SPACING.LG,
    alignItems: 'center',
  },
  providerButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  videoSection: {
    marginBottom: SPACING.XL,
  },
  videoContainer: {
    width: '100%',
    height: 200,
    borderRadius: BORDER_RADIUS.LG,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: SPACING.SM,
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
  },
  playButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -30 }, { translateY: -30 }],
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  downloadButton: {
    position: 'absolute',
    top: SPACING.MD,
    right: SPACING.MD,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: SPACING.SM,
    paddingVertical: 6,
  },
  downloadButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000000',
  },
  videoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: SPACING.MD,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  videoTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  videoDuration: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  videoPagination: {
    flexDirection: 'row',
    gap: SPACING.XS,
    justifyContent: 'center',
    marginTop: SPACING.SM,
  },
  videoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#CCCCCC',
  },
  videoDotActive: {
    backgroundColor: '#2196F3',
  },
  infoTabsContainer: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    marginBottom: SPACING.LG,
  },
  infoTab: {
    paddingVertical: SPACING.MD,
    paddingHorizontal: SPACING.LG,
    marginRight: SPACING.LG,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  infoTabActive: {
    borderBottomColor: '#2196F3',
  },
  infoTabText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666666',
  },
  infoTabTextActive: {
    color: '#2196F3',
    fontWeight: '600',
  },
  aboutContent: {
    marginBottom: SPACING.XL,
  },
  aboutItem: {
    fontSize: 15,
    lineHeight: 24,
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  feedbackSection: {
    marginBottom: SPACING.XL,
  },
  feedbackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.MD,
  },
  feedbackTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000000',
  },
  feedbackRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  feedbackRatingText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
  },
  reviewsList: {
    gap: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  reviewCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
  },
  reviewUserName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#000000',
    marginBottom: SPACING.XS,
  },
  reviewComment: {
    fontSize: 14,
    color: '#666666',
    marginBottom: SPACING.SM,
  },
  reviewFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewDate: {
    fontSize: 12,
    color: '#999999',
  },
  reviewRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewRatingText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  seeAllButton: {
    backgroundColor: '#E8F5E9',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
    alignItems: 'center',
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  recommendedSection: {
    marginTop: SPACING.LG,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.XL,
  },
  loadingText: {
    marginTop: SPACING.MD,
    fontSize: 16,
    color: '#666666',
  },
  outOfStockBadge: {
    marginTop: SPACING.SM,
    backgroundColor: '#FFEBEE',
    borderRadius: BORDER_RADIUS.SM,
    padding: SPACING.SM,
    alignItems: 'center',
  },
  outOfStockText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F44336',
  },
  addToCartButtonDisabled: {
    backgroundColor: '#CCCCCC',
    opacity: 0.6,
  },
  productSku: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.SM,
  },
  productBrand: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.XS,
  },
  productWeight: {
    fontSize: 14,
    color: '#666666',
    marginTop: SPACING.XS,
  },
});
