import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS, FONT_SIZES } from '@/constants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CART_ITEM_WIDTH = 363;
const CART_ITEM_HEIGHT = 140;
const CART_IMAGE_WIDTH = 108;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f3ec',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.XS,
  },
  backButton: {
    width: 40,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButtonBackground: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  iconButtonImage: {
    borderRadius: 18,
  },
  logoContainer: {
    flex: 1,
    alignItems: 'center',
  },
  placeholderButton: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: SPACING.XL,
  },
  screenTitle: {
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: '#001137',
    paddingHorizontal: SPACING.LG,
    marginTop: SPACING.MD,
    marginBottom: SPACING.SM,
  },
  warningBanner: {
    backgroundColor: '#edec80',
    borderRadius: 24,
    padding: SPACING.LG,
    marginHorizontal: SPACING.MD,
    marginBottom: SPACING.LG,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 8,
  },
  warningText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  productsTitle: {
    fontSize: FONT_SIZES.SM,
    fontWeight: '500',
    color: '#000000',
    opacity: 0.8,
    paddingHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
  },
  cartItemsList: {
    paddingHorizontal: SPACING.MD,
    gap: SPACING.MD,
  },
  cartItemCard: {
    backgroundColor: '#fbf7e5',
    borderRadius: 22,
    height: CART_ITEM_HEIGHT,
    width: CART_ITEM_WIDTH,
    position: 'relative',
    overflow: 'hidden',
  },
  itemImage: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: CART_IMAGE_WIDTH,
    height: CART_ITEM_HEIGHT,
    borderRadius: 22,
    backgroundColor: '#e0e0e0',
  },
  itemTagsRow: {
    position: 'absolute',
    left: 119,
    top: 15, // Tags ficam no topo (acima do título)
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 224,
  },
  itemHeaderContainer: {
    position: 'absolute',
    left: 119,
    top: 47, // Título fica abaixo das tags (15px top + 24px altura tags + 8px gap = ~47px)
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 23,
    width: 224,
  },
  itemInfo: {
    width: 151,
    flexShrink: 1,
  },
  itemTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    minHeight: 20,
    letterSpacing: 0.2,
    marginBottom: 0,
  },
  itemSubtitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    minHeight: 20,
    letterSpacing: 0.2,
    marginBottom: 0,
  },
  itemDate: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
    height: 20,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  ratingText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
  },
  tagsContainer: {
    flexDirection: 'row',
    gap: SPACING.SM,
    flexShrink: 1,
    minWidth: 0,
  },
  tagBadge: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 4,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
  },
  tagBadgeOrange: {
    // Background já definido acima
  },
  tagBadgeGreen: {
    // Background já definido acima
  },
  tagText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#f6dea9',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  tagTextOrange: {
    color: '#f6dea9',
  },
  tagTextGreen: {
    color: '#d8e4d6',
  },
  deleteButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  itemFooter: {
    position: 'absolute',
    left: 119,
    top: 95, // Baseado no design: 47 (header top) + 48px (gap)
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 224,
  },
  itemPrice: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    letterSpacing: 0.2,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
  },
  quantityButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#001137',
    minWidth: 24,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  shippingSection: {
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.MD,
    gap: SPACING.SM,
  },
  shippingTitle: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    marginBottom: SPACING.SM,
  },
  shippingInputRow: {
    flexDirection: 'row',
    gap: SPACING.MD,
    alignItems: 'flex-start',
  },
  zipCodeInput: {
    flex: 1,
    backgroundColor: '#fdfbee',
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    letterSpacing: 0.2,
  },
  applyButton: {
    backgroundColor: '#001137',
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  applyButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
  dontKnowZipButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  dontKnowZipText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    textDecorationLine: 'underline',
    letterSpacing: 0.2,
  },
  orderSummary: {
    paddingHorizontal: SPACING.LG,
    paddingTop: SPACING.MD,
    gap: SPACING.SM,
  },
  separator: {
    height: 1,
    backgroundColor: '#e1dfcf',
    marginVertical: SPACING.SM,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    letterSpacing: 0.2,
  },
  summaryValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#000000',
    textAlign: 'right',
    letterSpacing: 0.2,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: SPACING.SM,
  },
  totalLabel: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
  },
  totalValue: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
    textAlign: 'right',
  },
  buyButton: {
    width: 330,
    alignSelf: 'center',
    marginTop: SPACING.LG,
    marginBottom: SPACING.XL,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  loadingContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: FONT_SIZES.MD,
    color: '#666666',
  },
  emptyCartContainer: {
    padding: SPACING.XL,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
  },
  emptyCartText: {
    fontSize: FONT_SIZES.LG,
    fontWeight: '500',
    color: '#666666',
    marginBottom: SPACING.LG,
  },
  shopButton: {
    backgroundColor: '#001137',
    borderRadius: 24,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.MD,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shopButtonText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#ffffff',
    textAlign: 'center',
  },
});

