import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f3ec',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#001137',
    fontFamily: 'DM Sans',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  heroSection: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.6,
    position: 'relative',
    marginTop: -50,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroImageStyle: {
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 32,
    paddingBottom: 30,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  heroGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 327,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  heroContent: {
    zIndex: 1,
  },
  badgesContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    paddingHorizontal: 14,
    paddingVertical: 0,
    borderRadius: 16,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#f6dea9',
    letterSpacing: 0.2,
  },
  heroTitle: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#FFFFFF',
    marginTop: 10,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5,
    marginTop: -25,
    marginBottom: 20,
  },
  paginationDot: {
    width: 10,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: '#b2b2b2',
  },
  paginationDotActive: {
    backgroundColor: '#0154f8',
  },
  contentSection: {
    paddingHorizontal: 32,
    gap: 16,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 16,
  },
  tab: {
    paddingVertical: 9,
    paddingHorizontal: 16,
    minHeight: 36,
    borderRadius: 18,
    backgroundColor: '#fdfbee',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  tabActive: {
    backgroundColor: '#0154f8',
  },
  tabText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
  tabTextActive: {
    color: '#fbf7e5',
  },
  tabContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 64,
    borderTopLeftRadius: 64,
    borderTopRightRadius: 64,
    paddingHorizontal: 32,
    paddingVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
  },
  descriptionText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 22,
    marginLeft: 21,
  },
  otherOptionsSection: {
    gap: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#000000',
  },
  optionsList: {
    flexDirection: 'row',
    gap: 4,
    paddingLeft: 16,
  },
  optionItem: {
    alignItems: 'center',
    width: 74,
    gap: 8,
  },
  optionImage: {
    width: 69,
    height: 64,
    borderRadius: 8,
  },
  optionLabel: {
    fontSize: 8,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 22,
    textAlign: 'center',
    width: 86,
  },
  buySection: {
    gap: 10,
    alignItems: 'center',
  },
  buyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 48,
    width: 330,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  buyButtonText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: '#001137',
  },
  disclaimerText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: '#6e6a6a',
    lineHeight: 18.2,
    textAlign: 'center',
    width: 326,
  },
  learnMoreLink: {
    textDecorationLine: 'underline',
  },
});

