import { StyleSheet } from 'react-native';
import { COLORS, SPACING, FONT_SIZES, BORDER_RADIUS } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F3EC',
  },
  headerWrapper: {
    borderBottomLeftRadius: BORDER_RADIUS.ROUND,
    borderBottomRightRadius: BORDER_RADIUS.ROUND,
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.SM,
    gap: SPACING.MD,
    backgroundColor: COLORS.PRIMARY.LIGHT,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    flex: 1,
  },
  headerAvatar: {
    width: 52,
    height: 48,
    borderRadius: 24,
  },
  headerAvatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.PRIMARY.LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTextContainer: {
    flex: 1,
  },
  headerName: {
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  headerDescription: {
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.DARK,
    fontFamily: 'DM Sans',
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  messagesContainer: {
    flex: 1,
    backgroundColor: '#F4F3EC',
  },
  messagesContent: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.LG,
    flexGrow: 1,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.MD,
    gap: SPACING.SM,
    backgroundColor: COLORS.PRIMARY.LIGHT,
  },
  addButton: {
    width: 40,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  textInputWrapper: {
    flex: 1,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    borderRadius: 20,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  textInput: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.SECONDARY.LIGHT,
    letterSpacing: 0.2,
    padding: 0,
    minHeight: 20,
  },
  inputContainerDisabled: {
    opacity: 0.5,
  },
  textInputWrapperDisabled: {
    backgroundColor: COLORS.NEUTRAL.LOW.MEDIUM,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: SPACING.MD,
  },
  emptyText: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    fontFamily: 'DM Sans',
    textAlign: 'center',
  },
});
