import { StyleSheet } from 'react-native';
import { COLORS, SPACING, FONT_SIZES } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    gap: SPACING.MD,
  },
  backButton: {
    width: 40,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    flex: 1,
  },
  headerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  headerAvatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.PRIMARY.LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTextContainer: {
    flex: 1,
  },
  headerName: {
    fontSize: FONT_SIZES.XL,
    fontWeight: '700',
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    lineHeight: 22,
  },
  headerDescription: {
    fontSize: FONT_SIZES.XS,
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.DARK,
    fontFamily: 'DM Sans',
    lineHeight: 22,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    flexGrow: 1,
  },
  messageBubble: {
    maxWidth: '80%',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.MD,
    marginBottom: SPACING.XS,
  },
  messageBubbleReceived: {
    alignSelf: 'flex-start',
    backgroundColor: '#F0EEE1',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 32,
  },
  messageBubbleSent: {
    alignSelf: 'flex-end',
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 4,
  },
  messageText: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  messageTextReceived: {
    color: COLORS.NEUTRAL.LOW.DARK,
  },
  messageTextSent: {
    color: COLORS.SECONDARY.LIGHT,
  },
  messageTimestamp: {
    fontSize: 10,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.NEUTRAL.LOW.DARK,
    lineHeight: 20,
    marginBottom: SPACING.SM,
  },
  messageTimestampReceived: {
    alignSelf: 'flex-start',
    marginLeft: SPACING.XS,
  },
  messageTimestampSent: {
    alignSelf: 'flex-end',
    marginRight: SPACING.XS,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    paddingBottom: SPACING.MD,
    gap: SPACING.SM,
    backgroundColor: COLORS.PRIMARY.LIGHT,
  },
  addButton: {
    width: 40,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  textInputWrapper: {
    flex: 1,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    borderRadius: 18,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  textInput: {
    fontSize: FONT_SIZES.SM,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.SECONDARY.LIGHT,
    letterSpacing: 0.2,
    padding: 0,
  },
  sendButton: {
    width: 40,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.NEUTRAL.LOW.PURE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: SPACING.MD,
  },
  emptyText: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    fontFamily: 'DM Sans',
    textAlign: 'center',
  },
});
