import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
  },
  card: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: COLORS.SECONDARY.PURE,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.MD,
    paddingHorizontal: SPACING.MD,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
    paddingBottom: SPACING.SM,
  },
  closeHit: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 16,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: COLORS.NEUTRAL.LOW.PURE,
    textAlign: 'center',
    width: '100%',
    marginBottom: SPACING.MD,
  },
  body: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.NEUTRAL.LOW.PURE,
    letterSpacing: 0.2,
    textAlign: 'center',
    width: '100%',
    marginBottom: SPACING.LG,
    lineHeight: 20,
  },
  cta: {
    width: '100%',
    minHeight: 36,
    paddingVertical: 9,
    paddingHorizontal: SPACING.MD,
    borderRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: '#F0EEE1',
    borderWidth: 1,
    borderColor: COLORS.NEUTRAL.LOW.PURE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  ctaLabel: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.PURE,
    textAlign: 'center',
  },
});
