import { StyleSheet } from 'react-native';
import { SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    gap: 8,
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: "100%",
    alignSelf: 'center',
    paddingHorizontal: SPACING.XL,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: '#001137',
  },
  checkContainer: {
    width: 30,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#8fa3a1',
  },
  videoCard: {
    width: "100%",
    height: 500,
    borderRadius: 64,
    borderTopLeftRadius: 64,
    borderTopRightRadius: 64,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
    alignSelf: 'center',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(1, 84, 248, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoInfo: {
    position: 'absolute',
    bottom: 60,
    left: 24,
    right: 24,
    gap: 8,
  },
  videoTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  videoDuration: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '400',
  },
  actions: {
    position: 'absolute',
    top: 28,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#fbf7e5',
    paddingVertical: 9,
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    minHeight: 36,
  },
  downloadButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#fbf7e5',
  },
  volumeButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(240, 238, 225, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

