import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  infoSection: {
    width: '100%',
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    paddingHorizontal: 0,
  },
  infoText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 24,
    textAlign: 'left',
    paddingBottom: SPACING.MD,
  },
  sectionLabel: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: SPACING.SM,
  },
  fieldsContainer: {
    width: '100%',
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  fieldRow: {
    width: '100%',
    alignSelf: 'stretch',
  },
  genderLabel: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 22,
    marginBottom: 8,
  },
  genderLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  requiredMark: {
    color: '#e30f3c',
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
  },
  genderTouchable: {
    alignSelf: 'stretch',
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderRadius: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 42,
  },
  genderTouchableText: {
    color: COLORS.TEXT,
    fontFamily: 'DM Sans',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 20,
    flex: 1,
  },
  genderPlaceholder: {
    color: COLORS.TEXT_LIGHT,
  },
  genderModalOverlay: {
    flex: 1,
    backgroundColor: COLORS.BLACK + '80',
    justifyContent: 'flex-end',
  },
  genderModalContent: {
    backgroundColor: COLORS.BACKGROUND,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.XXL + 24,
  },
  genderModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.LG,
  },
  genderModalTitle: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 18,
    fontWeight: '600',
  },
  genderOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.MD,
    paddingHorizontal: SPACING.SM,
    borderRadius: 12,
    marginBottom: SPACING.XS,
  },
  genderOptionSelected: {
    backgroundColor: 'rgba(1, 84, 248, 0.08)',
  },
  genderOptionText: {
    color: COLORS.NEUTRAL.LOW.PURE,
    fontFamily: 'DM Sans',
    fontSize: 16,
    fontWeight: '400',
    flex: 1,
  },
  genderOptionTextSelected: {
    fontWeight: '600',
    color: COLORS.PRIMARY.PURE,
  },
  fieldErrorText: {
    color: '#e30f3c',
    fontFamily: 'DM Sans',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.2,
    lineHeight: 22,
    marginTop: 4,
  },
});
