import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

const CARD_CORNER_RADIUS = {
  borderTopLeftRadius: 24,
  borderTopRightRadius: 28,
  borderBottomLeftRadius: 12,
  borderBottomRightRadius: 32,
} as const;

export const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    height: 148,
    width: '100%',
    gap: SPACING.SM,
    paddingHorizontal: SPACING.MD,
  },
  lessonCard: {
    width: 139,
    height: 148,
    ...CARD_CORNER_RADIUS,
    overflow: 'hidden',
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  lessonImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  lessonOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  lessonBadge: {
    backgroundColor: '#fdfbee',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
  },
  lessonBadgeText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.PURE,
    textAlign: 'center',
  },
  eventCard: {
    flex: 1,
    minWidth: 0,
    height: 148,
    backgroundColor: 'rgba(237, 236, 128, 0.8)',
    ...CARD_CORNER_RADIUS,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.SM,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  eventContent: {
    flex: 1,
    justifyContent: 'center',
    gap: SPACING.LG,
  },
  eventTextBlock: {
    gap: SPACING.SM,
  },
  eventMessage: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.NEUTRAL.LOW.PURE,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  eventLiveLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.NEUTRAL.LOW.PURE,
    letterSpacing: 0.2,
  },
});
