import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZES, SPACING, BORDER_RADIUS } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  content: {
    flex: 1,
  },
  tabsContainer: {
    paddingHorizontal: SPACING.MD,
  },
  filtersContainer: {
    marginBottom: SPACING.MD,
    gap: SPACING.SM,
    paddingHorizontal: SPACING.MD,
  },
  createButtonContainer: {
    alignSelf: 'flex-start',
  },
  createButton: {
    alignSelf: 'flex-start',
  },
  eventReminderContainer: {
    marginHorizontal: SPACING.MD,
  },
  anamnesisPromptContainer: {
    paddingTop: SPACING.MD,
  },
  sectionLabel: {
    fontSize: FONT_SIZES.XS,
    color: COLORS.TEXT_LIGHT,
    marginBottom: SPACING.SM,
    marginTop: SPACING.XS,
    paddingHorizontal: SPACING.MD,
  },
  scrollContent: {
    paddingBottom: SPACING.XL,
  },
  activityCard: {
    backgroundColor: '#fbf7e5',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    paddingTop: SPACING.MD,
    paddingBottom: SPACING.LG,
    paddingHorizontal: SPACING.MD,
    marginBottom: SPACING.MD,
    marginHorizontal: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 4,
  },
  appointmentCard: {
    backgroundColor: '#FFFFFF',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgeContainer: {
    width: 110,
  },
  typeBadge: {
    backgroundColor: '#FFF9C4',
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    borderRadius: BORDER_RADIUS.SM,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  appointmentBadge: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    borderRadius: BORDER_RADIUS.SM,
    borderWidth: 1,
    borderColor: '#C8E6C9',
  },
  typeBadgeText: {
    fontSize: FONT_SIZES.XS,
    color: COLORS.TEXT,
    fontWeight: '500',
  },
  cardContent: {
    gap: SPACING.LG,
    marginBottom: SPACING.SM,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    flexWrap: 'wrap',
    marginBottom: SPACING.XS,
  },
  starIcon: {
    marginRight: SPACING.XS,
  },
  dateTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    marginRight: SPACING.XS,
  },
  dateTimeText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#6e6a6a',
    letterSpacing: 0.2,
    lineHeight: 14,
  },
  cardTitle: {
    fontSize: FONT_SIZES.LG,
    fontWeight: 'bold',
    color: COLORS.TEXT,
    flex: 1,
  },
  cardDescription: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    lineHeight: 20,
  },
  appointmentDateTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    marginBottom: SPACING.SM,
  },
  appointmentDateTimeText: {
    fontSize: FONT_SIZES.MD,
    fontWeight: 'bold',
    color: COLORS.TEXT,
  },
  providerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginBottom: SPACING.SM,
  },
  providerText: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
  },
  providerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerAvatarText: {
    fontSize: FONT_SIZES.SM,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  providerName: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
  },
  cardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  actionButton: {
    flexDirection: 'row',
    borderRadius: BORDER_RADIUS.MD,
    gap: SPACING.XS,
  },
  markButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  doneButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  doneButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  openButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: '#001137',
    borderRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: SPACING.MD,
    paddingVertical: 9,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  openButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#001137',
    textAlign: 'center',
  },
  viewLink: {
    fontSize: 12,
    fontWeight: '500',
    color: '#0154f8',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  skipLink: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  recommendationsCard: {
    backgroundColor: '#FFF9C4',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.LG,
    marginTop: SPACING.LG,
    marginBottom: SPACING.MD,
  },
  recommendationsTitle: {
    fontSize: FONT_SIZES.XL,
    fontWeight: 'bold',
    color: COLORS.TEXT,
    marginBottom: SPACING.XS,
  },
  recommendationsSubtitle: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    marginBottom: SPACING.SM,
  },
  recommendationsDescription: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT,
    lineHeight: 20,
    marginBottom: SPACING.MD,
  },
  anamnesisButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFF9C4',
    paddingVertical: SPACING.MD,
    paddingHorizontal: SPACING.LG,
    borderRadius: BORDER_RADIUS.MD,
    alignItems: 'center',
  },
  anamnesisButtonText: {
    fontSize: FONT_SIZES.MD,
    color: COLORS.TEXT,
    fontWeight: '600',
  },
  section: {
    marginTop: SPACING.LG,
    marginBottom: SPACING.MD,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.LG,
    fontWeight: 'bold',
    color: COLORS.TEXT,
    marginBottom: SPACING.XS,
  },
  sectionSubtitle: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT_LIGHT,
    marginBottom: SPACING.MD,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: SPACING.XL,
  },
  emptyText: {
    fontSize: FONT_SIZES.MD,
    color: COLORS.TEXT_LIGHT,
    textAlign: 'center',
  },
  carouselWrapper: {
    marginTop: SPACING.SM,
  },
  statusIcon: {
    width: 40,
    height: 36,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  menuContainer: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: SPACING.XS,
    minWidth: 120,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.SM,
    gap: SPACING.SM,
  },
  menuItemText: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.TEXT,
    fontWeight: '500',
  },
  menuItemTextDanger: {
    color: '#F44336',
  },
});
