import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.SECONDARY.PURE,
    borderRadius: 22,
    paddingRight: 16,
    gap: 12,
    shadowColor: COLORS.BLACK,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  image: {
    width: 108,
    height: 140,
    borderRadius: 22,
    backgroundColor: COLORS.NEUTRAL.LOW.MEDIUM,
  },
  content: {
    flex: 1,
    gap: 10,
    justifyContent: 'space-between',
    minWidth: 0,
    marginVertical: SPACING.SM,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  topRowRight: {
    flexShrink: 0,
  },
  badgesWrap: {
    flexDirection: 'row',
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'DM Sans',
    color: COLORS.PRIMARY.LIGHT,
    letterSpacing: 0.2,
  },
  middleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    width: '100%',
    gap: 8,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
  },
  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  priceBlock: {
    flexShrink: 0,
    justifyContent: 'center',
  },
  title: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'DM Sans',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  price: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'DM Sans',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  outOfStock: {
    fontSize: 12,
    color: COLORS.ERROR,
    fontWeight: '600',
  },
  deleteButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subtitle: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
    marginTop: 2,
  },
  ratingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  ratingText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  quantityButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    minWidth: 24,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
});
