import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '@/constants';

export const PRODUCT_ROW_CARD_HEIGHT = 122;

export const styles = StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'stretch',
    height: PRODUCT_ROW_CARD_HEIGHT,
    overflow: 'hidden',
    backgroundColor: COLORS.SECONDARY.PURE,
    borderRadius: 22,
    gap: 12,
    shadowColor: COLORS.BLACK,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  imageColumn: {
    width: 108,
    height: PRODUCT_ROW_CARD_HEIGHT,
    borderRadius: 22,
    backgroundColor: COLORS.NEUTRAL.LOW.MEDIUM,
  },
  contentColumn: {
    flex: 1,
    gap: 8,
    justifyContent: 'space-between',
    minWidth: 0,
    overflow: 'hidden',
    paddingVertical: SPACING.MD_PLUS,
  },
  actionColumn: {
    flexShrink: 0,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingRight: 16,
    paddingVertical: SPACING.MD,
    minWidth: 44,
  },
  actionColumnStacked: {
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  badgesWrap: {
    flexDirection: 'row',
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
    paddingTop: SPACING.XS,
  },
  badge: {
    backgroundColor: 'rgba(0, 17, 55, 0.64)',
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 24,
    maxWidth: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'DM Sans',
    color: COLORS.PRIMARY.LIGHT,
    letterSpacing: 0.2,
  },
  titleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    width: '100%',
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    gap: 8,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  priceBlock: {
    flexShrink: 0,
    justifyContent: 'center',
  },
  title: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'DM Sans',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
    flexShrink: 1,
  },
  price: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'DM Sans',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  outOfStock: {
    fontSize: 12,
    color: COLORS.ERROR,
    fontWeight: '600',
  },
  deleteButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subtitle: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
    marginTop: 2,
    flexShrink: 1,
  },
  ratingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  ratingText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  quantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  quantityButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    minWidth: 24,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
});
