import { StyleSheet } from 'react-native';
import { SPACING, BORDER_RADIUS } from '@/constants';

const COLORS = {
  TEXT_DARK: '#001137',
  TEXT_LIGHT: '#666666',
  PRIMARY: '#0154f8',
  BORDER: '#b2b2b2',
  BLACK: '#000000',
};

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.MD,
  },
  modalContainer: {
    backgroundColor: 'rgba(251, 247, 229, 0.96)',
    borderRadius: BORDER_RADIUS.XL,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    width: '100%',
    maxWidth: 360,
    maxHeight: '80%',
    paddingTop: SPACING.SM,
    paddingBottom: SPACING.MD,
    paddingHorizontal: SPACING.MD,
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.MD,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.TEXT_DARK,
  },
  closeButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flex: 1,
    marginBottom: SPACING.MD,
  },
  section: {
    marginBottom: SPACING.LG,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.TEXT_DARK,
    marginBottom: SPACING.SM,
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.XS,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251, 247, 229, 0.8)',
    borderRadius: BORDER_RADIUS.MD,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: SPACING.MD,
    gap: 9,
    minWidth: 140,
    flexBasis: '47%',
    shadowColor: COLORS.BLACK,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  filterOptionSelected: {
    backgroundColor: 'rgba(240, 238, 225, 0.9)',
    borderWidth: 1,
    borderColor: COLORS.PRIMARY,
  },
  optionIcon: {
    fontSize: 16,
  },
  optionText: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.TEXT_DARK,
    flex: 1,
  },
  optionTextSelected: {
    fontWeight: '500',
    color: COLORS.PRIMARY,
  },
  authorInput: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: BORDER_RADIUS.MD,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingVertical: 9,
    paddingHorizontal: SPACING.MD,
    minHeight: 36,
    justifyContent: 'center',
  },
  authorPlaceholder: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.TEXT_LIGHT,
  },
  saveButton: {
    backgroundColor: 'rgba(240, 238, 225, 0.16)',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: BORDER_RADIUS.MD,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingVertical: 9,
    paddingHorizontal: SPACING.MD,
    minHeight: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: SPACING.SM,
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.TEXT_DARK,
  },
  saveButtonTextDisabled: {
    color: COLORS.TEXT_LIGHT,
  },
});

