import { StyleSheet } from 'react-native';
import { BORDER_RADIUS, COLORS, SPACING } from '@/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  scrollContent: {
    paddingHorizontal: SPACING.LG,
    paddingBottom: SPACING.XXL,
    paddingTop: SPACING.LG,
    gap: SPACING.XL,
  },
  heroCard: {
    backgroundColor: '#001137',
    borderRadius: 36,
    padding: SPACING.XL,
    gap: SPACING.MD,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 999,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.XS,
  },
  heroBadgeText: {
    color: COLORS.WHITE,
    fontWeight: '600',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontSize: 12,
  },
  heroTitle: {
    color: COLORS.WHITE,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 32,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 15,
    lineHeight: 22,
  },
  heroStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: SPACING.SM,
  },
  heroStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
  },
  heroStatValue: {
    color: COLORS.WHITE,
    fontSize: 20,
    fontWeight: '700',
  },
  heroStatLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    marginTop: 4,
  },
  searchWrapper: {
    marginTop: -SPACING.MD,
  },
  filtersHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    backgroundColor: '#FBF7E5',
    borderRadius: BORDER_RADIUS.LG,
    padding: SPACING.MD,
  },
  filtersHintText: {
    flex: 1,
    fontSize: 13,
    color: '#001137',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SPACING.LG,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#001137',
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sectionActionText: {
    color: '#001137',
    fontSize: 13,
    fontWeight: '600',
  },
  categoriesList: {
    gap: SPACING.SM,
    paddingVertical: SPACING.SM,
  },
  categoryPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dcd7c8',
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.SM,
    backgroundColor: COLORS.WHITE,
    marginRight: SPACING.SM,
  },
  categoryPillSelected: {
    backgroundColor: '#001137',
    borderColor: '#001137',
  },
  categoryText: {
    fontSize: 14,
    color: '#001137',
    fontWeight: '500',
  },
  categoryTextSelected: {
    color: COLORS.WHITE,
  },
  featuredCard: {
    flexDirection: 'row',
    backgroundColor: '#FFF3D9',
    borderRadius: 32,
    padding: SPACING.LG,
    gap: SPACING.LG,
  },
  featuredContent: {
    flex: 1,
    gap: SPACING.SM,
  },
  featuredEyebrow: {
    fontSize: 12,
    color: '#B26A00',
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  featuredTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#3b2c0f',
    lineHeight: 26,
  },
  featuredDescription: {
    fontSize: 14,
    color: '#6e5a2a',
    lineHeight: 20,
  },
  featuredHighlights: {
    gap: SPACING.SM,
  },
  featuredHighlightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
  },
  featuredHighlightText: {
    fontSize: 13,
    color: '#3b2c0f',
  },
  featuredButton: {
    marginTop: SPACING.SM,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.SM,
    borderRadius: BORDER_RADIUS.LG,
  },
  featuredButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#001137',
  },
  featuredImageWrapper: {
    width: 120,
    height: 160,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: COLORS.WHITE,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: SPACING.LG,
  },
  productCard: {
    width: '48%',
    backgroundColor: COLORS.WHITE,
    borderRadius: 24,
    padding: SPACING.MD,
    gap: SPACING.SM,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  productImageHolder: {
    borderRadius: 20,
    overflow: 'hidden',
    height: 120,
    marginBottom: SPACING.SM,
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  productBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: SPACING.SM,
    paddingVertical: 4,
    borderRadius: 999,
  },
  productBadgeText: {
    color: COLORS.WHITE,
    fontSize: 12,
    fontWeight: '600',
  },
  productTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#001137',
  },
  productPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3b2c0f',
  },
  productRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  productRatingText: {
    fontSize: 12,
    color: '#6f6c66',
  },
  bundleList: {
    gap: SPACING.MD,
    paddingVertical: SPACING.SM,
  },
  bundleCard: {
    width: 260,
    backgroundColor: '#E8F1ED',
    borderRadius: 28,
    padding: SPACING.LG,
    marginRight: SPACING.MD,
    gap: SPACING.SM,
  },
  bundleBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0,17,55,0.08)',
    paddingHorizontal: SPACING.MD,
    paddingVertical: 4,
    borderRadius: 999,
  },
  bundleBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#001137',
  },
  bundleTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#001137',
  },
  bundleDescription: {
    fontSize: 14,
    color: '#4f4a43',
    lineHeight: 20,
  },
  bundleFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SPACING.SM,
  },
  bundlePrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#001137',
  },
  bundleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SPACING.MD,
    paddingVertical: SPACING.XS,
    borderRadius: BORDER_RADIUS.LG,
  },
  bundleButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#001137',
  },
  newsletterCard: {
    backgroundColor: '#001137',
    borderRadius: 32,
    padding: SPACING.XL,
    gap: SPACING.SM,
  },
  newsletterTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.WHITE,
    lineHeight: 28,
  },
  newsletterSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
    lineHeight: 20,
  },
  newsletterButton: {
    marginTop: SPACING.SM,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.SM,
    borderRadius: BORDER_RADIUS.LG,
  },
  newsletterButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#001137',
  },
});
