import { StyleSheet } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS } from '@/constants';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: SPACING.XL * 2,
  },
  markerHeaderSection: {
    paddingHorizontal: SPACING.MD,
    paddingTop: SPACING.LG,
    paddingBottom: SPACING.SM,
  },
  markerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.SM,
  },
  markerName: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
  },
  markerProgressContainer: {
    marginTop: SPACING.SM,
    width: '100%',
  },
  mainStatsCard: {
    backgroundColor: COLORS.SECONDARY.PURE,
    marginHorizontal: SPACING.MD,
    marginTop: SPACING.MD,
    padding: SPACING.LG,
    borderRadius: BORDER_RADIUS.XL,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  mainStatsTitle: {
    fontSize: 24,
    fontFamily: 'Bricolage Grotesque',
    fontWeight: '700',
    color: COLORS.BLACK,
    textTransform: 'uppercase',
    marginBottom: SPACING.LG,
  },
  insightsSection: {
    marginBottom: SPACING.LG,
  },
  insightsTitle: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: COLORS.BLACK,
    marginBottom: SPACING.SM,
  },
  insightsText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.BLACK,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: SPACING.MD,
  },
  metricCard: {
    flex: 1,
    backgroundColor: COLORS.SECONDARY.LIGHT,
    borderRadius: 24,
    padding: SPACING.MD,
    justifyContent: 'space-between',
    minHeight: 120,
  },
  metricLabel: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '600',
    color: COLORS.TEXT,
    marginBottom: SPACING.XS,
  },
  metricValue: {
    fontSize: 72,
    fontFamily: 'Bricolage Grotesque',
    fontWeight: '400',
    color: COLORS.TEXT,
    textAlign: 'center',
    lineHeight: 80,
    includeFontPadding: false,
  },
  routineCard: {
    marginHorizontal: SPACING.MD,
    marginTop: SPACING.MD,
  },
  routineTitle: {
    fontSize: 24,
    fontFamily: 'Bricolage Grotesque',
    fontWeight: '700',
    color: COLORS.TEXT,
  },
  routineContent: {
    gap: SPACING.SM,
  },
  routineSubtitle: {
    fontSize: 20,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.TEXT,
    marginBottom: SPACING.SM,
  },
  routineText: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  historyCard: {
    backgroundColor: COLORS.SECONDARY.PURE,
    marginHorizontal: SPACING.MD,
    paddingHorizontal: SPACING.LG,
    paddingVertical: SPACING.XXL,
    borderRadius: BORDER_RADIUS.XL,
    borderTopLeftRadius: 64,
    borderTopRightRadius: 64,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  historyTitle: {
    fontSize: 16,
    fontFamily: 'DM Sans',
    fontWeight: '700',
    color: COLORS.TEXT,
    marginBottom: SPACING.LG,
  },
  periodSelector: {
    marginBottom: SPACING.LG,
  },
  chartContainer: {
    flexDirection: 'row',
    gap: SPACING.XS,
    alignItems: 'flex-end',
  },
  chartBarContainer: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
    justifyContent: 'flex-end',
  },
  chartBarWrapper: {
    width: '100%',
    height: 243,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: SPACING.XS,
  },
  chartBar: {
    width: 30,
    minHeight: 30,
    borderRadius: 4,
    marginBottom: SPACING.XS,
  },
  chartDayLabel: {
    fontSize: 14,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.BLACK,
    letterSpacing: -0.28,
    marginTop: SPACING.XS,
    textAlign: 'center',
  },
  chartDateLabel: {
    fontSize: 12,
    fontFamily: 'DM Sans',
    fontWeight: '400',
    color: COLORS.TEXT_LIGHT,
    letterSpacing: -0.24,
    textAlign: 'center',
    marginTop: 2,
    lineHeight: 12.6,
  },
  chartValueDot: {
    position: 'absolute',
    top: -27,
    alignSelf: 'center',
    width: 27,
    height: 27,
    borderRadius: 13.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chartValueText: {
    fontSize: 10,
    fontFamily: 'DM Sans',
    fontWeight: '500',
    color: COLORS.TEXT,
  },
});
